In [1]:
import numpy as np

In [2]:
X = np.array([[1,1],[1,2],[2,1],[2,2],[10,10],[10,11],[11,10],[11,11]]).T.astype(float)
C = np.array([[1,1],[10,10]]).T.astype(float)

m = X.shape[1]
k = C.shape[1]

In [3]:
def assign_clusters(X, C):
    # X: d x n data matrix
    # C: d x k cluster center matrix
    # return: 1 x n array of cluster assignments
    n = X.shape[1]
    k = C.shape[1]
    assignments = np.zeros(n, dtype=int)
    for i in range(n):
        distances = np.linalg.norm(X[:, i].reshape(-1, 1) - C, axis=0)
        assignments[i] = np.argmin(distances)
    return assignments

centers = C

for i in range(10):
    print(f"Iteration {i+1}")
    # Assign clusters
    assignments = assign_clusters(X, centers)
    print("Assignments:\n", assignments)
    # Update cluster centers
    for j in range(k):
        points_in_cluster = X[:, assignments == j]
        print(f"Cluster {j+1} points:\n", points_in_cluster)
        if points_in_cluster.shape[1] > 0:
            centers[:, j] = np.mean(points_in_cluster, axis=1)
    print("Updated Centers:\n", centers)

Iteration 1
Assignments:
 [0 0 0 0 1 1 1 1]
Cluster 1 points:
 [[1. 1. 2. 2.]
 [1. 2. 1. 2.]]
Cluster 2 points:
 [[10. 10. 11. 11.]
 [10. 11. 10. 11.]]
Updated Centers:
 [[ 1.5 10.5]
 [ 1.5 10.5]]
Iteration 2
Assignments:
 [0 0 0 0 1 1 1 1]
Cluster 1 points:
 [[1. 1. 2. 2.]
 [1. 2. 1. 2.]]
Cluster 2 points:
 [[10. 10. 11. 11.]
 [10. 11. 10. 11.]]
Updated Centers:
 [[ 1.5 10.5]
 [ 1.5 10.5]]
Iteration 3
Assignments:
 [0 0 0 0 1 1 1 1]
Cluster 1 points:
 [[1. 1. 2. 2.]
 [1. 2. 1. 2.]]
Cluster 2 points:
 [[10. 10. 11. 11.]
 [10. 11. 10. 11.]]
Updated Centers:
 [[ 1.5 10.5]
 [ 1.5 10.5]]
Iteration 4
Assignments:
 [0 0 0 0 1 1 1 1]
Cluster 1 points:
 [[1. 1. 2. 2.]
 [1. 2. 1. 2.]]
Cluster 2 points:
 [[10. 10. 11. 11.]
 [10. 11. 10. 11.]]
Updated Centers:
 [[ 1.5 10.5]
 [ 1.5 10.5]]
Iteration 5
Assignments:
 [0 0 0 0 1 1 1 1]
Cluster 1 points:
 [[1. 1. 2. 2.]
 [1. 2. 1. 2.]]
Cluster 2 points:
 [[10. 10. 11. 11.]
 [10. 11. 10. 11.]]
Updated Centers:
 [[ 1.5 10.5]
 [ 1.5 10.5]]
Iteration 6
Ass

In [4]:
C = np.array([[1,1],[2,2]]).T.astype(float)

In [5]:
from fractions import Fraction
# k-means++ initialization
n = X.shape[1]
centers = np.zeros((X.shape[0], k))
centers[:, 0] = X[:, 0]  # choose one initial center
# compute squared distances to the chosen center using integer arithmetic
# X and centers are float but originally integer coordinates
# diff shape: (d, n)
diff = X - centers[:, 0].reshape(-1, 1)
sq_dists = (diff[0]**2 + diff[1]**2).astype(int)  # exact integers
# total for denominator
den = int(sq_dists.sum())
# build Fraction objects
fractions = [Fraction(d, den) for d in sq_dists]
probabilities = sq_dists / den  # float probabilities
print("Squared distances:", sq_dists)
print("Probabilities (float):", probabilities)
print("Probabilities (fraction):", [f"{f.numerator}/{f.denominator}" for f in fractions])

Squared distances: [  0   1   1   2 162 181 181 200]
Probabilities (float): [0.         0.00137363 0.00137363 0.00274725 0.22252747 0.24862637
 0.24862637 0.27472527]
Probabilities (fraction): ['0/1', '1/728', '1/728', '1/364', '81/364', '181/728', '181/728', '25/91']


In [6]:
from fractions import Fraction
# k-means++ initialization
n = X.shape[1]
centers = np.zeros((X.shape[0], k))
centers[:, 0] = X[:, 0]  # choose one initial center
centers[:, 1] = X[:, 4]
# compute squared distances to the chosen center using integer arithmetic
# X and centers are float but originally integer coordinates
# diff shape: (d, n)
diff = X - centers[:, 0].reshape(-1, 1)
sq_dists = (diff[0]**2 + diff[1]**2).astype(int)  # exact integers
diff2 = X - centers[:, 1].reshape(-1, 1)
sq_dists2 = (diff2[0]**2 + diff2[1]**2).astype(int)  # exact integers
sq_dists = np.minimum(sq_dists, sq_dists2)
# total for denominator
den = int(sq_dists.sum())
# build Fraction objects
fractions = [Fraction(d, den) for d in sq_dists]
probabilities = sq_dists / den  # float probabilities
print("Minimum Squared distances:", sq_dists)
print("Probabilities (float):", probabilities)
print("Probabilities (fraction):", [f"{f.numerator}/{f.denominator}" for f in fractions])

Minimum Squared distances: [0 1 1 2 0 1 1 2]
Probabilities (float): [0.    0.125 0.125 0.25  0.    0.125 0.125 0.25 ]
Probabilities (fraction): ['0/1', '1/8', '1/8', '1/4', '0/1', '1/8', '1/8', '1/4']


In [7]:
A = np.array([[0.6, 0.4], [0.3, 0.7]])
B = np.array([[0.8, 0.2], [0.3, 0.7]])
pi = np.array([0.4, 0.6])

In [8]:
alpha = np.zeros((2, 4), dtype=float)
alpha[:, 0] = pi * B[:, 0]
alpha

array([[0.32, 0.  , 0.  , 0.  ],
       [0.18, 0.  , 0.  , 0.  ]])

In [9]:
alpha[:, 1] = (alpha[:, 0] @ A) * B[:, 1]
alpha[:, 2] = (alpha[:, 1] @ A) * B[:, 0]
alpha[:, 3] = (alpha[:, 2] @ A) * B[:, 1]
alpha

array([[0.32      , 0.0492    , 0.066288  , 0.01054908],
       [0.18      , 0.1778    , 0.043242  , 0.03974922]])

In [10]:
beta = np.zeros((2, 4), dtype=float)
beta[:, 3] = 1.0
beta[:, 2] = (A @ (B[:, 1] * beta[:, 3]))
beta[:, 1] = (A @ (B[:, 0] * beta[:, 2]))
beta[:, 0] = (A @ (B[:, 1] * beta[:, 1]))
beta

array([[0.09018 , 0.258   , 0.4     , 1.      ],
       [0.119115, 0.2115  , 0.55    , 1.      ]])

In [ ]:
gamma = np.zeros((2, 4), dtype=float)
for t in range(4):
    gamma[:, t] = (alpha[:, t] * beta[:, t]) / np.sum(alpha[:, t] * beta[:, t])
gamma

array([[0.57372913, 0.25236638, 0.52715897, 0.20973035],
       [0.42627087, 0.74763362, 0.47284103, 0.79026965]])

In [20]:
x = np.array([0, 1, 0, 1])
xi = np.zeros((3, 2, 2), dtype=float)
for t in range(3):
    denom = np.sum(alpha[:, t] * beta[:, t])
    for i in range(2):
        numer = alpha[i, t] * A[i, :] * B[:, x[t+1]] * beta[:, t+1]
        xi[t, i, :] = numer / denom
xi

array([[[0.19696888, 0.37676025],
        [0.0553975 , 0.37087337]],

       [[0.18780754, 0.06455884],
        [0.33935143, 0.40828219]],

       [[0.15814769, 0.36901128],
        [0.05158266, 0.42125837]]])

In [22]:
pi_new = gamma[:, 0]
pi_new

array([0.57372913, 0.42627087])

In [23]:
a_new = np.sum(xi, axis=0) / np.sum(gamma[:, :-1], axis=1).reshape(-1, 1)
a_new

array([[0.40119883, 0.59880117],
       [0.27103859, 0.72896141]])

In [24]:
b_new = np.zeros((2, 2), dtype=float)
for j in range(2):
    for k in range(2):
        numer = np.sum(gamma[j, x == k])
        denom = np.sum(gamma[j, :])
        b_new[j, k] = numer / denom
b_new

array([[0.70434983, 0.29565017],
       [0.3689398 , 0.6310602 ]])